# Generated by Django 2.2.5 on 2019-09-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBO_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(default=None, max_length=24),
        ),
    ]
